sources:
    osm:
        type: Raster
        url: 	https://a.tile.openstreetmap.org/{z}/{x}/{y}.png 

layers:
    BaseLayer:
        data:
            source: osm
        draw:
            BaseStyle:
                style: raster
                order: 0
