sources:
    osm:
        type: Raster
        url: 	https://a.tile.openstreetmap.org/{z}/{x}/{y}.png 

layers:
    _terrainLayer:
        data:
            source: osm
            # But this time since raster data is loaded as an image, no need to declare a 'layer' parameter
        draw:
            _terainStyle:
                style: raster # Remember Tangram comes with a prebuilt set of styles for different data types: points, polygons, lines, text, and raster. For raster sources we need to use the 'raster' keyword
                order: 0 # draw on bottom
